[package]
name = "pong"
version = "0.1.0"
authors = ["Vincent Siles <vincent.siles@gmail.com>"]
edition = "2018"

[dependencies]
ggez = "0.5"
cgmath = { version = "0.17", features = ["mint"] }
rand = "0.7"
