[package]
name = "pong"
version = "0.1.0"
authors = ["Vincent Siles <vincent.siles@gmail.com>"]
edition = "2018"

[dependencies]
ggez = "0.9.2"
cgmath = { version = "0.18", features = ["mint"] }
rand = "0.8.5"
